### ISSUE TITLE
Xcode Version 11.0 beta 6 (11M392r) 模拟器报错

### ISSUE THREAD

**Issue by TheLittleBoy** [aliyunvideo/AliyunPlayer_iOS#20]
Xcode Version 11.0 beta 6 (11M392r) 模拟器上播放视频的时候一直疯狂输出此报错信息。不知道有没有人预计见过。

`Error at CVOpenGLESTextureCacheCreateTextureFromImage -6683`

视频画面是一片绿。

**Comment by Wayyy** [comment]
我也是

**Comment by TheLittleBoy** [comment]
@Wayyy  我已经使用最新的4.X版本的SDK了。 升级指南：https://help.aliyun.com/document_detail/124709.html
